### ISSUE TITLE
Morning session: Peer-to-peer code review

### ISSUE THREAD

**Issue by Aduda-Boaz** [Sahar-AbdelSamad/Awesome-Books#4]
Nice to have your project completed and approved.
The code is clean and readable. Keep up the good work.
Congratulations

**Comment by Sahar-AbdelSamad** [comment]
Thank you @Aduda-Boaz  for your kind words! Glad you liked it 
![image](https://user-images.githubusercontent.com/87965534/148554064-058d086f-7d00-4562-af4c-8d97d5626531.png)
